export const testimonials = [
  {
    id: 1,
    name: "Priya Singh",
    role: "Daily Commuter",
    image: "https://i.pravatar.cc/150?img=1",
    text: "ZUNO helped me navigate Jaipur's traffic! 30 minutes instead of 2 hours. ⚡",
    rating: 5,
  },
  {
    id: 2,
    name: "Rahul Patel",
    role: "Student",
    image: "https://i.pravatar.cc/150?img=2",
    text: "Affordable way to explore Jaipur. Love riding through the Pink City! 💚",
    rating: 5,
  },
  {
    id: 3,
    name: "Ananya Verma",
    role: "Freelancer",
    image: "https://i.pravatar.cc/150?img=3",
    text: "Perfect for Jaipur's first & last mile mobility needs.",
    rating: 4.5,
  },
  {
    id: 4,
    name: "Arjun Kumar",
    role: "IT Professional",
    image: "https://i.pravatar.cc/150?img=4",
    text: "App works smoothly in Jaipur. Bikes always available at stations!",
    rating: 5,
  },
  {
    id: 5,
    name: "Neha Gupta",
    role: "Business Owner",
    image: "https://i.pravatar.cc/150?img=5",
    text: "Game changer for Jaipur connectivity. No more parking hassles!",
    rating: 5,
  },
];
